version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-npm-{{ checksum "package.json" }}
          - v1-npm-

      - restore_cache:
          keys:
          - v1-bower-{{ checksum "bower.json" }}
          - v1-bower-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - bower_components
          key: v1-bower-{{ checksum "bower.json" }}

      - run: npm test

      - store_test_results:
          path: ./test-results
